# Generated by Django 3.1.5 on 2021-02-18 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default='siteimages/blankUser.png', upload_to='account/mugshots/'),
        ),
    ]
