# Generated by Django 3.1.5 on 2021-03-23 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_profile_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='opt_in_to_email',
            field=models.BooleanField(default=False),
        ),
    ]
