# Generated by Django 3.1.5 on 2021-03-23 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_profile_opt_in_to_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='opt_in_to_email',
            field=models.BooleanField(default=True),
        ),
    ]
