# Generated by Django 3.1.5 on 2021-03-25 13:37

import account.formatChecker
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20210323_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=account.formatChecker.ContentTypeRestrictedFileField(default='siteimages/blankUser.png', upload_to='account/mugshots/'),
        ),
    ]
