# Generated by Django 3.1.5 on 2021-02-10 13:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademyScoringMatrix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pointsType', models.CharField(max_length=1)),
                ('formula', models.CharField(max_length=1)),
                ('role', models.CharField(max_length=1)),
                ('multiplier', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Competitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mugshot', models.ImageField(upload_to='mugshots/')),
                ('surname', models.CharField(max_length=20)),
                ('firstname', models.CharField(max_length=20)),
                ('role', models.CharField(default='D', max_length=1)),
                ('formula', models.CharField(max_length=1)),
                ('team', models.CharField(blank=True, max_length=20)),
                ('value', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('nationality', models.CharField(blank=True, max_length=20)),
                ('championships', models.IntegerField(default=0)),
                ('pointsPreviousSeasons', models.IntegerField(default=0)),
                ('winsPreviousSeasons', models.IntegerField(default=0)),
                ('polesPreviousSeasons', models.IntegerField(default=0)),
                ('pointsThisSeason', models.IntegerField(default=0)),
                ('winsThisSeason', models.IntegerField(default=0)),
                ('polesThisSeason', models.IntegerField(default=0)),
                ('gainLossThisseason', models.IntegerField(default=0)),
                ('fastestLapsThisSeason', models.IntegerField(default=0)),
                ('webLink', models.CharField(blank=True, max_length=30)),
                ('instaHandle', models.CharField(blank=True, max_length=30)),
                ('twitterHandle', models.CharField(blank=True, max_length=30)),
                ('short_bio', models.TextField(blank=True, default=' ')),
            ],
            options={
                'verbose_name': 'Driver or Manager',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('date', models.DateField()),
                ('circuit', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=20)),
                ('formulas', models.CharField(max_length=40)),
                ('startDateTime', models.DateTimeField()),
                ('endDateTime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scoringEvent_ID', models.IntegerField()),
                ('competitor_ID', models.IntegerField()),
                ('finishPosition', models.IntegerField()),
                ('startPosition', models.IntegerField()),
                ('lapOrRaceTime', models.IntegerField()),
                ('lapsComplete', models.IntegerField()),
                ('formulaPoints', models.IntegerField()),
                ('pole', models.BooleanField(default=False)),
                ('fastestLap', models.BooleanField(default=False)),
                ('placesGainedLost', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ScoringMatches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_ID', models.IntegerField()),
                ('result_ID', models.IntegerField()),
                ('points_Type', models.CharField(max_length=1)),
                ('academyPoints', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TeamProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamName', models.CharField(max_length=20)),
                ('teamLogo', models.ImageField(default='siteimages/blankUser.jpg', upload_to='mugshots/')),
                ('dateStarted', models.DateField()),
                ('user_ID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ScoringEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('formula', models.CharField(max_length=1)),
                ('eventType', models.CharField(max_length=1)),
                ('event_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='season.event')),
            ],
        ),
    ]
