# Generated by Django 3.1.5 on 2021-01-29 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competitors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mugshot', models.ImageField(upload_to='mugshots/')),
                ('surname', models.CharField(max_length=20)),
                ('firstname', models.CharField(max_length=20)),
                ('role', models.CharField(max_length=1)),
                ('formula', models.CharField(max_length=1)),
                ('team', models.CharField(max_length=20)),
                ('value', models.IntegerField()),
                ('nationality', models.CharField(max_length=20)),
                ('birthdate', models.DateField()),
                ('wins', models.IntegerField()),
                ('poles', models.IntegerField()),
                ('championships', models.IntegerField()),
                ('pointsThisSeason', models.IntegerField()),
                ('winsThisSeason', models.IntegerField()),
                ('polesThisSeason', models.IntegerField()),
                ('gainLossThisseason', models.IntegerField()),
                ('webLink', models.CharField(max_length=30)),
                ('instaHandle', models.CharField(max_length=30)),
                ('twitterHandle', models.CharField(max_length=30)),
            ],
        ),
    ]
