# Generated by Django 3.1.5 on 2021-02-10 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('season', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Result',
        ),
        migrations.RemoveField(
            model_name='scoringevent',
            name='event_ID',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='ScoringEvent',
        ),
    ]
