# Generated by Django 3.1.5 on 2021-02-11 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('season', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academyscoringmatrix',
            name='formula',
            field=models.CharField(choices=[('1', 'Formula 1'), ('2', 'Formula 2'), ('3', 'Formula 3'), ('W', 'W Series')], max_length=1),
        ),
        migrations.AlterField(
            model_name='competitor',
            name='formula',
            field=models.CharField(choices=[('1', 'Formula 1'), ('2', 'Formula 2'), ('3', 'Formula 3'), ('W', 'W Series')], max_length=1),
        ),
        migrations.AlterField(
            model_name='result',
            name='competitor_ID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='season.competitor'),
        ),
        migrations.AlterField(
            model_name='result',
            name='scoringEvent_ID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='season.scoringevent'),
        ),
        migrations.AlterField(
            model_name='scoringevent',
            name='formula',
            field=models.CharField(choices=[('1', 'Formula 1'), ('2', 'Formula 2'), ('3', 'Formula 3'), ('W', 'W Series')], max_length=1),
        ),
        migrations.AlterField(
            model_name='scoringmatches',
            name='player_ID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='season.teamprofile'),
        ),
        migrations.AlterField(
            model_name='scoringmatches',
            name='result_ID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='season.result'),
        ),
        migrations.AlterField(
            model_name='teamprofile',
            name='teamLogo',
            field=models.ImageField(default='siteimages/blankUser.png', upload_to='mugshots/'),
        ),
    ]
