# Generated by Django 3.1.5 on 2021-01-29 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('season', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Competitors',
            new_name='Competitor',
        ),
        migrations.AlterModelOptions(
            name='competitor',
            options={'verbose_name': 'Driver or Manager'},
        ),
    ]
