# Generated by Django 3.1.5 on 2021-02-10 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('season', '0002_auto_20210210_1403'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('date', models.DateField()),
                ('circuit', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=20)),
                ('formulas', models.CharField(max_length=40)),
                ('startDateTime', models.DateTimeField()),
                ('endDateTime', models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='scoringmatches',
            name='player_ID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='season.teamprofile'),
        ),
        migrations.CreateModel(
            name='ScoringEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('formula', models.CharField(max_length=1)),
                ('eventType', models.CharField(max_length=1)),
                ('event_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='season.event')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finishPosition', models.IntegerField()),
                ('startPosition', models.IntegerField()),
                ('lapOrRaceTime', models.IntegerField()),
                ('lapsComplete', models.IntegerField()),
                ('formulaPoints', models.IntegerField()),
                ('pole', models.BooleanField(default=False)),
                ('fastestLap', models.BooleanField(default=False)),
                ('placesGainedLost', models.IntegerField()),
                ('competitor_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='season.competitor')),
                ('scoringEvent_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='season.scoringevent')),
            ],
        ),
        migrations.AlterField(
            model_name='scoringmatches',
            name='result_ID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='season.result'),
        ),
    ]
