# Generated by Django 3.1.5 on 2021-02-12 14:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('season', '0002_scoringevent_startdatetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamprofile',
            name='user_ID',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='team', to=settings.AUTH_USER_MODEL),
        ),
    ]
