# Generated by Django 3.1.5 on 2021-01-29 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('season', '0002_auto_20210129_1742'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('circuit', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=20)),
                ('formula', models.CharField(max_length=1)),
            ],
        ),
    ]
