# Generated by Django 3.1.5 on 2021-01-29 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('season', '0003_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventID', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='competitor',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
