# Generated by Django 3.1.5 on 2021-01-29 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('season', '0004_auto_20210129_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitor',
            name='value',
            field=models.DecimalField(decimal_places=1, max_digits=9),
        ),
    ]
