# Generated by Django 3.1.5 on 2021-02-13 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('season', '0004_auto_20210213_1810'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ('date',)},
        ),
    ]
