# Generated by Django 3.1.5 on 2021-02-13 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('season', '0005_auto_20210213_1811'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='competitor',
            options={'ordering': ('-value',), 'verbose_name': 'Driver or Manager'},
        ),
        migrations.AlterField(
            model_name='competitor',
            name='role',
            field=models.CharField(choices=[('D', 'Driver'), ('M', 'Manager')], max_length=1),
        ),
    ]
