# Generated by Django 3.1.5 on 2021-01-29 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('season', '0005_auto_20210129_1901'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Result',
        ),
        migrations.AddField(
            model_name='competitor',
            name='raceNumber',
            field=models.IntegerField(default='2'),
        ),
        migrations.AlterField(
            model_name='competitor',
            name='value',
            field=models.DecimalField(decimal_places=1, max_digits=4),
        ),
    ]
