# Generated by Django 3.1.5 on 2021-01-29 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('season', '0006_auto_20210129_2000'),
    ]

    operations = [
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventID', models.IntegerField()),
                ('competitor', models.IntegerField()),
                ('formula', models.CharField(max_length=1)),
                ('raceOrQuali', models.CharField(max_length=1)),
                ('position', models.IntegerField()),
                ('timeSeconds', models.DecimalField(decimal_places=3, max_digits=8)),
                ('lapsComplete', models.IntegerField()),
                ('points', models.IntegerField()),
                ('pole', models.BooleanField(null=True)),
                ('fastestLap', models.BooleanField(null=True)),
                ('placesGainedLost', models.IntegerField()),
                ('gridPosition', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='competitor',
            name='raceNumber',
            field=models.IntegerField(default='0'),
        ),
    ]
