# Generated by Django 3.1.5 on 2021-01-31 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('season', '0007_auto_20210129_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitor',
            name='championships',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='competitor',
            name='gainLossThisseason',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='competitor',
            name='instaHandle',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='competitor',
            name='nationality',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='competitor',
            name='pointsThisSeason',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='competitor',
            name='poles',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='competitor',
            name='polesThisSeason',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='competitor',
            name='raceNumber',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='competitor',
            name='role',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='competitor',
            name='twitterHandle',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='competitor',
            name='value',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='competitor',
            name='webLink',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='competitor',
            name='wins',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='competitor',
            name='winsThisSeason',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='result',
            name='fastestLap',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='result',
            name='pole',
            field=models.BooleanField(default=False),
        ),
    ]
