# Generated by Django 3.1.5 on 2021-02-14 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('season', '0007_auto_20210214_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='formulaPoints',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='result',
            name='lapOrRaceTime',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='result',
            name='lapsComplete',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='result',
            name='placesGainedLost',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='result',
            name='startPosition',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='scoringevent',
            name='eventType',
            field=models.CharField(choices=[('Q', 'Qualifying'), ('R', 'Race'), ('1', 'Race 1'), ('2', 'Race 2'), ('F', 'Feature Race'), ('S', 'Sprint Race')], max_length=1),
        ),
    ]
