# Generated by Django 3.1.5 on 2021-01-31 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('season', '0008_auto_20210131_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitor',
            name='role',
            field=models.CharField(max_length=1),
        ),
    ]
