# Generated by Django 3.1.5 on 2021-01-31 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('season', '0009_auto_20210131_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitor',
            name='role',
            field=models.CharField(max_length=2),
        ),
    ]
