# Generated by Django 3.1.5 on 2021-01-31 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('season', '0010_auto_20210131_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitor',
            name='role',
            field=models.CharField(max_length=1),
        ),
    ]
