# Generated by Django 3.1.5 on 2021-02-18 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('season', '0011_auto_20210217_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamprofile',
            name='teamLogo',
            field=models.ImageField(default='siteimages/car_outline.jpg', upload_to='mugshots/'),
        ),
        migrations.AlterField(
            model_name='teamprofile',
            name='teamName',
            field=models.CharField(default='My Team', max_length=20),
        ),
    ]
