# Generated by Django 3.1.5 on 2021-02-01 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('season', '0011_auto_20210131_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitor',
            name='short_bio',
            field=models.TextField(default=' '),
        ),
    ]
