# Generated by Django 3.1.5 on 2021-02-04 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('season', '0012_competitor_short_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competitor',
            name='raceNumber',
        ),
        migrations.AlterField(
            model_name='competitor',
            name='birthdate',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='competitor',
            name='formula',
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AlterField(
            model_name='competitor',
            name='mugshot',
            field=models.ImageField(blank=True, upload_to='mugshots/'),
        ),
        migrations.AlterField(
            model_name='competitor',
            name='role',
            field=models.CharField(blank=True, default='D', max_length=1),
        ),
        migrations.AlterField(
            model_name='competitor',
            name='short_bio',
            field=models.TextField(blank=True, default=' '),
        ),
        migrations.AlterField(
            model_name='competitor',
            name='team',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
