# Generated by Django 3.1.5 on 2021-02-04 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('season', '0013_auto_20210204_1346'),
    ]

    operations = [
        migrations.RenameField(
            model_name='competitor',
            old_name='winsThisSeason',
            new_name='fastestLapsThisSeason',
        ),
        migrations.RemoveField(
            model_name='competitor',
            name='birthdate',
        ),
        migrations.AddField(
            model_name='competitor',
            name='pointsPreviousSeasons',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='competitor',
            name='winsPreviousSeasons',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='competitor',
            name='formula',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='competitor',
            name='role',
            field=models.CharField(default='D', max_length=1),
        ),
    ]
