# Generated by Django 3.1.5 on 2021-02-21 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('season', '0014_auto_20210219_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamprofile',
            name='dateSelected',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='teamprofile',
            name='p1_1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='p1_1', to='season.competitor'),
        ),
        migrations.AddField(
            model_name='teamprofile',
            name='p1_2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='p1_2', to='season.competitor'),
        ),
        migrations.AddField(
            model_name='teamprofile',
            name='p1_m',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='p1_m', to='season.competitor'),
        ),
        migrations.AddField(
            model_name='teamprofile',
            name='p2_1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='p2_1', to='season.competitor'),
        ),
        migrations.AddField(
            model_name='teamprofile',
            name='p2_2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='p2_2', to='season.competitor'),
        ),
        migrations.AddField(
            model_name='teamprofile',
            name='p2_m',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='p2_m', to='season.competitor'),
        ),
        migrations.AddField(
            model_name='teamprofile',
            name='p3_1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='p3_1', to='season.competitor'),
        ),
        migrations.AddField(
            model_name='teamprofile',
            name='p3_2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='p3_2', to='season.competitor'),
        ),
        migrations.AddField(
            model_name='teamprofile',
            name='p3_m',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='p3_m', to='season.competitor'),
        ),
        migrations.AddField(
            model_name='teamprofile',
            name='pw_1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pw_1', to='season.competitor'),
        ),
        migrations.AddField(
            model_name='teamprofile',
            name='pw_2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pw_2', to='season.competitor'),
        ),
        migrations.AddField(
            model_name='teamprofile',
            name='pw_m',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pw_m', to='season.competitor'),
        ),
    ]
