# Generated by Django 3.1.5 on 2021-02-04 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('season', '0015_competitor_winsthisseason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competitor',
            name='poles',
        ),
        migrations.RemoveField(
            model_name='competitor',
            name='wins',
        ),
    ]
