# Generated by Django 3.1.5 on 2021-02-22 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('season', '0015_auto_20210221_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamprofile',
            name='p1_1_cost',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4),
        ),
        migrations.AddField(
            model_name='teamprofile',
            name='p1_2_cost',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4),
        ),
        migrations.AddField(
            model_name='teamprofile',
            name='p1_m_cost',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4),
        ),
        migrations.AddField(
            model_name='teamprofile',
            name='p2_1_cost',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4),
        ),
        migrations.AddField(
            model_name='teamprofile',
            name='p2_2_cost',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4),
        ),
        migrations.AddField(
            model_name='teamprofile',
            name='p2_m_cost',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4),
        ),
        migrations.AddField(
            model_name='teamprofile',
            name='p3_1_cost',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4),
        ),
        migrations.AddField(
            model_name='teamprofile',
            name='p3_2_cost',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4),
        ),
        migrations.AddField(
            model_name='teamprofile',
            name='p3_m_cost',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4),
        ),
        migrations.AddField(
            model_name='teamprofile',
            name='pw_1_cost',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4),
        ),
        migrations.AddField(
            model_name='teamprofile',
            name='pw_2_cost',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4),
        ),
        migrations.AddField(
            model_name='teamprofile',
            name='pw_m_cost',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4),
        ),
    ]
