# Generated by Django 3.1.5 on 2021-02-05 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('season', '0016_auto_20210204_1411'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademyScoringMatrix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pointsType', models.CharField(max_length=1)),
                ('formula', models.CharField(max_length=1)),
                ('role', models.CharField(max_length=1)),
                ('multiplier', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='ScoringEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_ID', models.IntegerField()),
                ('name', models.CharField(max_length=40)),
                ('formula', models.CharField(max_length=1)),
                ('eventType', models.CharField(max_length=1)),
                ('startDateTime', models.DateTimeField()),
                ('endDateTime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ScoringMatches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_ID', models.IntegerField()),
                ('result_ID', models.IntegerField()),
                ('points_Type', models.CharField(max_length=1)),
                ('academyPoints', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='Result',
        ),
        migrations.AddField(
            model_name='competitor',
            name='polesPreviousSeasons',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='competitor',
            name='mugshot',
            field=models.ImageField(upload_to='mugshots/'),
        ),
    ]
