# Generated by Django 3.1.5 on 2021-02-27 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('season', '0016_auto_20210222_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoringevent',
            name='results_in',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='competitor',
            name='mugshot',
            field=models.ImageField(default='siteimages/blankUser.png', upload_to='mugshots/'),
        ),
        migrations.AlterField(
            model_name='teamprofile',
            name='p1_m',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='p1_m', to='season.competitor'),
        ),
        migrations.AlterField(
            model_name='teamprofile',
            name='p2_m',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='p2_m', to='season.competitor'),
        ),
        migrations.AlterField(
            model_name='teamprofile',
            name='p3_m',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='p3_m', to='season.competitor'),
        ),
        migrations.AlterField(
            model_name='teamprofile',
            name='pw_m',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pw_m', to='season.competitor'),
        ),
    ]
