# Generated by Django 3.1.5 on 2021-02-27 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('season', '0017_auto_20210227_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamprofile',
            name='f1_cashpot',
            field=models.DecimalField(decimal_places=1, default=50.0, max_digits=4),
        ),
        migrations.AddField(
            model_name='teamprofile',
            name='f2_cashpot',
            field=models.DecimalField(decimal_places=1, default=30.0, max_digits=4),
        ),
        migrations.AddField(
            model_name='teamprofile',
            name='f3_cashpot',
            field=models.DecimalField(decimal_places=1, default=20.0, max_digits=4),
        ),
        migrations.AddField(
            model_name='teamprofile',
            name='ws_cashpot',
            field=models.DecimalField(decimal_places=1, default=20.0, max_digits=4),
        ),
    ]
