# Generated by Django 3.1.5 on 2021-03-07 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('season', '0018_auto_20210227_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scoringevent',
            name='eventType',
            field=models.CharField(choices=[('Q', 'Qualifying'), ('R', 'Race'), ('1', 'Race 1'), ('2', 'Race 2'), ('3', 'Race 3'), ('F', 'Feature Race'), ('S', 'Sprint Race')], max_length=1),
        ),
    ]
