# Generated by Django 3.1.5 on 2021-02-05 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('season', '0018_event_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='formulas',
            field=models.CharField(max_length=40),
        ),
    ]
