# Generated by Django 3.1.5 on 2021-02-08 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('season', '0020_teamprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teamprofile',
            old_name='used_ID',
            new_name='user_ID',
        ),
    ]
