# Generated by Django 3.1.5 on 2021-02-10 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('season', '0021_auto_20210208_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamprofile',
            name='teamLogo',
            field=models.ImageField(default='siteimages/blankUser.jpg', upload_to='mugshots/'),
        ),
    ]
