# Generated by Django 3.1.5 on 2021-03-10 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('season', '0021_result_disqualified'),
    ]

    operations = [
        migrations.AddField(
            model_name='academyscoringmatrix',
            name='q_disqualified',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
