# Generated by Django 3.1.5 on 2021-03-11 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('season', '0024_competitorscore_scoringevent_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamscore',
            name='scoringevent_ID',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='teamscore',
            name='cscore_ID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cscore', to='season.competitorscore'),
        ),
    ]
