# Generated by Django 3.1.5 on 2021-03-11 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('season', '0025_auto_20210311_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamscore',
            name='eventType',
            field=models.CharField(choices=[('Q', 'Qualifying'), ('R', 'Race'), ('1', 'Race 1'), ('2', 'Race 2'), ('3', 'Race 3'), ('F', 'Feature Race'), ('S', 'Sprint Race')], default='Q', max_length=1),
        ),
    ]
