# Generated by Django 3.1.5 on 2021-03-11 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('season', '0026_teamscore_eventtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamscore',
            name='driver_ID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='driver', to='season.competitor'),
        ),
        migrations.AddField(
            model_name='teamscore',
            name='formula',
            field=models.CharField(default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='result',
            name='competitor_ID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='competitor', to='season.competitor'),
        ),
    ]
