# Generated by Django 3.1.5 on 2021-03-13 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('season', '0028_auto_20210313_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamprofile',
            name='teamLogo',
            field=models.ImageField(default='siteimages/defaultTeam.png', upload_to='mugshots/'),
        ),
    ]
