# Generated by Django 3.1.5 on 2021-03-13 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('season', '0029_auto_20210313_1522'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='competitor',
            options={'ordering': ('-value',), 'verbose_name': 'Driver'},
        ),
        migrations.AddField(
            model_name='scoringevent',
            name='resultsArray',
            field=models.TextField(default='-'),
        ),
    ]
