# Generated by Django 3.1.5 on 2021-03-15 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('season', '0030_auto_20210313_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitor',
            name='previousHistory',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
