# Generated by Django 3.1.5 on 2021-03-17 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('season', '0031_competitor_previoushistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitor',
            name='points_dsq',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='competitor',
            name='points_fl',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='competitor',
            name='points_lbl',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='competitor',
            name='points_pgl',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='competitor',
            name='points_pos',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='competitor',
            name='points_total',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='competitorscore',
            name='competitor_ID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cscore_driver', to='season.competitor'),
        ),
        migrations.AddField(
            model_name='teamprofile',
            name='points_f1',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='teamprofile',
            name='points_f2',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='teamprofile',
            name='points_f3',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='teamprofile',
            name='points_f4',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='teamprofile',
            name='points_total',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='teamscore',
            name='competitor_ID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tscore_driver', to='season.competitor'),
        ),
        migrations.AlterField(
            model_name='teamprofile',
            name='pw_m_cost',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5),
        ),
    ]
