# Generated by Django 3.1.5 on 2021-03-17 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('season', '0032_auto_20210317_1315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teamscore',
            name='competitor_ID',
        ),
    ]
