# Generated by Django 3.1.5 on 2021-03-19 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('season', '0033_remove_teamscore_competitor_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teamprofile',
            old_name='points_f4',
            new_name='points_ws',
        ),
    ]
