# Generated by Django 3.1.5 on 2021-03-19 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('season', '0034_auto_20210319_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamprofile',
            name='league_position',
            field=models.IntegerField(default=0),
        ),
    ]
