# Generated by Django 3.1.5 on 2021-03-20 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('season', '0036_parameter'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameter',
            name='explanation',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
