# Generated by Django 3.1.5 on 2021-03-21 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('season', '0037_parameter_explanation'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameter',
            name='long_text',
            field=models.TextField(blank=True, default=' '),
        ),
        migrations.AddField(
            model_name='parameter',
            name='text',
            field=models.CharField(default=' ', max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='parameter',
            name='value',
            field=models.IntegerField(default=0),
        ),
    ]
