# Generated by Django 3.1.5 on 2021-03-21 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('season', '0038_auto_20210321_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameter',
            name='text',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
