# Generated by Django 3.1.5 on 2021-03-25 13:37

from django.db import migrations, models
import season.formatChecker


class Migration(migrations.Migration):

    dependencies = [
        ('season', '0039_auto_20210321_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitor',
            name='mugshot',
            field=season.formatChecker.ContentTypeRestrictedFileField(default='siteimages/blankUser.png', upload_to='mugshots/'),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='text',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='teamprofile',
            name='teamLogo',
            field=season.formatChecker.ContentTypeRestrictedFileField(default='siteimages/defaultTeam.png', upload_to='mugshots/'),
        ),
    ]
