# Generated by Django 3.1.5 on 2021-04-10 15:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('season', '0042_auto_20210403_2205'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamArchive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamName', models.CharField(default='My Team', max_length=30)),
                ('dateArchived', models.DateTimeField(auto_now=True)),
                ('f1_cashpot', models.DecimalField(decimal_places=1, default=50.0, max_digits=4)),
                ('f2_cashpot', models.DecimalField(decimal_places=1, default=30.0, max_digits=4)),
                ('f3_cashpot', models.DecimalField(decimal_places=1, default=20.0, max_digits=4)),
                ('ws_cashpot', models.DecimalField(decimal_places=1, default=20.0, max_digits=4)),
                ('p1_1_cost', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('p1_2_cost', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('p1_m_cost', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('p2_1_cost', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('p2_2_cost', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('p2_m_cost', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('p3_1_cost', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('p3_2_cost', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('p3_m_cost', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('pw_1_cost', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('pw_2_cost', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('pw_m_cost', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('points_total', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('p1_1', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='a_p1_1', to='season.competitor')),
                ('p1_2', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='a_p1_2', to='season.competitor')),
                ('p1_m', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='a_p1_m', to='season.competitor')),
                ('p2_1', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='a_p2_1', to='season.competitor')),
                ('p2_2', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='a_p2_2', to='season.competitor')),
                ('p2_m', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='a_p2_m', to='season.competitor')),
                ('p3_1', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='a_p3_1', to='season.competitor')),
                ('p3_2', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='a_p3_2', to='season.competitor')),
                ('p3_m', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='a_p3_m', to='season.competitor')),
                ('pw_1', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='a_pw_1', to='season.competitor')),
                ('pw_2', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='a_pw_2', to='season.competitor')),
                ('pw_m', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='a_pw_m', to='season.competitor')),
                ('user_ID', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='archive', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
