# Generated by Django 3.1.5 on 2021-04-10 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('season', '0043_teamarchive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamarchive',
            name='f1_cashpot',
            field=models.DecimalField(decimal_places=1, max_digits=4),
        ),
        migrations.AlterField(
            model_name='teamarchive',
            name='f2_cashpot',
            field=models.DecimalField(decimal_places=1, max_digits=4),
        ),
        migrations.AlterField(
            model_name='teamarchive',
            name='f3_cashpot',
            field=models.DecimalField(decimal_places=1, max_digits=4),
        ),
        migrations.AlterField(
            model_name='teamarchive',
            name='teamName',
            field=models.CharField(default='My Team Archive', max_length=30),
        ),
        migrations.AlterField(
            model_name='teamarchive',
            name='ws_cashpot',
            field=models.DecimalField(decimal_places=1, max_digits=4),
        ),
    ]
