# Generated by Django 3.1.5 on 2021-04-10 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('season', '0044_auto_20210410_1533'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teamarchive',
            old_name='dateArchived',
            new_name='dateSelected',
        ),
        migrations.AlterField(
            model_name='teamarchive',
            name='f1_cashpot',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='teamarchive',
            name='f2_cashpot',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='teamarchive',
            name='f3_cashpot',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='teamarchive',
            name='ws_cashpot',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4),
        ),
    ]
