# Generated by Django 3.1.5 on 2021-05-13 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('season', '0045_auto_20210410_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='topDriverScore',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='event',
            name='topTeamScore',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.CreateModel(
            name='TeamWeekendScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_f1', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('points_f2', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('points_f3', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('points_ws', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('points_total', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('position_f1', models.IntegerField(default=0)),
                ('position_f2', models.IntegerField(default=0)),
                ('position_f3', models.IntegerField(default=0)),
                ('position_ws', models.IntegerField(default=0)),
                ('position_total', models.IntegerField(default=0)),
                ('points_f1_since', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('points_f2_since', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('points_f3_since', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('points_ws_since', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('points_total_since', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('position_f1_since', models.IntegerField(default=0)),
                ('position_f2_since', models.IntegerField(default=0)),
                ('position_f3_since', models.IntegerField(default=0)),
                ('position_ws_since', models.IntegerField(default=0)),
                ('position_total_since', models.IntegerField(default=0)),
                ('team_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='season.teamprofile')),
                ('weekend', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='season.event')),
            ],
        ),
        migrations.CreateModel(
            name='DriverWeekendScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formula', models.CharField(choices=[('1', 'Formula 1'), ('2', 'Formula 2'), ('3', 'Formula 3'), ('W', 'W Series')], max_length=1)),
                ('points_this_weekend', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('posn_this_weekend', models.IntegerField(default=0)),
                ('driver_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='season.competitor')),
                ('weekend', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='season.event')),
            ],
        ),
    ]
