# Generated by Django 3.1.5 on 2021-05-14 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('season', '0046_auto_20210513_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='topF1DriverScore',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='event',
            name='topF2DriverScore',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='event',
            name='topF3DriverScore',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='event',
            name='topWSDriverScore',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
